[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -std=c++17
    -Iinclude

[env:native]
platform = native
build_flags =
    -std=c++17
    -Iinclude
test_framework = unity
